name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest # Cambiar a windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to IIS
        run: |
          robocopy ./ "C:\inetpub\wwwroot" /e
        shell: cmd
